---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: kafka-producer
      demo: client
      kubecon: demo
      kafka-operator: inject-credentials
    annotations:
      "topic.kafka.nb/produces": "sample-topic"
    name: kafka-producer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: kafka-producer
    template:
      metadata:
        labels:
          app: kafka-producer
          demo: client
      spec:
        containers:
        - env:
          - name: JAVA_MAIN_CLASS
            value: nb.kubecon.KafkaProducerSample
          - name: JAVA_OPTIONS
            value: "-Djava.security.auth.login.config=/opt/kafka/auth/kafka-client-jaas.conf"
          - name: USE_ACL
            value: "true"
          image: nbogojevic/kafka-clients
          imagePullPolicy: IfNotPresent
          name: nbogojevic-kafka-clients
          securityContext:
            privileged: false
          volumeMounts:        
          - name: kafka-credentials
            mountPath: /opt/kafka/auth
        volumes:      
        - name: kafka-credentials
          secret:
            secretName: kafka-producer-kafka-credentials
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: kafka-consumer
      demo: client
      kubecon: demo
      kafka-operator: inject-credentials
    annotations:
      "topic.kafka.nb/consumes": "sample-topic"
    name: kafka-consumer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: kafka-consumer
    template:
      metadata:
        labels:
          app: kafka-consumer
          demo: client
      spec:
        containers:
        - env:
          - name: JAVA_MAIN_CLASS
            value: nb.kubecon.KafkaConsumerSample
          - name: JAVA_OPTIONS
            value: "-Djava.security.auth.login.config=/opt/kafka/auth/kafka-client-jaas.conf"
          - name: USE_ACL
            value: "true"
          image: nbogojevic/kafka-clients
          imagePullPolicy: IfNotPresent
          name: nbogojevic-kafka-clients
          securityContext:
            privileged: false
          volumeMounts:        
          - name: kafka-credentials
            mountPath: /opt/kafka/auth
        volumes:      
        - name: kafka-credentials
          secret:
            secretName: kafka-consumer-kafka-credentials