---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: kafka-producer
      demo: client
      kubecon: demo
    name: kafka-producer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: kafka-producer
    template:
      metadata:
        labels:
          app: kafka-producer
          demo: client
      spec:
        containers:
        - env:
          - name: JAVA_MAIN_CLASS
            value: nb.kubecon.KafkaProducerSample
          image: nbogojevic/kafka-clients
          imagePullPolicy: IfNotPresent
          name: nbogojevic-kafka-clients
          securityContext:
            privileged: false
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: kafka-consumer
      demo: client
      kubecon: demo
    name: kafka-consumer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: kafka-consumer
    template:
      metadata:
        labels:
          app: kafka-consumer
          demo: client
      spec:
        containers:
        - env:
          - name: JAVA_MAIN_CLASS
            value: nb.kubecon.KafkaConsumerSample
          image: nbogojevic/kafka-clients
          imagePullPolicy: IfNotPresent
          name: nbogojevic-kafka-clients
          securityContext:
            privileged: false
