apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-topic
  labels:
    config: kafka-topic
    demo: client
    kubecon: demo
data:
  partitions: "20"
  replication-factor: "1"
  properties: |
    retention.ms=1000000
